apiVersion: v1
kind: Secret
metadata:
    name: grafana-auth-secrets
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:2L649HgLUom0GJO5Moc+YEMMTYg/zkkSXMc5sXiuL8iW0YFLXNyPxA==,iv:9qKCUOxb4jJiL1n3n0GCiawnJTfJxXcuZYpUiqzlmkY=,tag:M+L6oRSspOSUdW3DY4595Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8qcxU13uedBsj3Ufdk5oTT/5Yt9PVuBIaq40YTxsg1/GZ/jMAz7YC4f7LeBHdeya8ACbqiXr0z7esVqGjlzdwKBOSiB9T+4uOnnduaMJXEOwO5ICVel3PEjnRfVsYpzThjCP5tadmFT2xG1a4nNiXolIXg/uqDq8l+i1F6qz6SM=,iv:uK1Q+GKQZJGg48ratqDlb9iOtLmhWZw140SfnxqBcq4=,tag:BDj1li3gAT9faw5EOUNBgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTU1ScFNxb29MN3pqTkw2
            NytRcFljRy93UmpFTW8zNTNwNmlHbnJBa1cwCkFKYk1tdUV1MFF1MWRDZHBaMjR0
            WXBSem9OL0djU1lwbVdVNGZjbXVBVjAKLS0tIDZXSWUzZTJ1NkZHY1VSYzk2Y3NE
            RUxQNUEwVW1UTExVMU0xcEd0Y1MrSUEKuXVtsgzAiRt4kajjuZUjrNho+ew2lJsf
            8RZ2LT9mZ4DJ5+3ttKdDVIdoVQRZMi8RGrZJo02bvhCocT/6bZjUZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T10:20:44Z"
    mac: ENC[AES256_GCM,data:51TO6C8osL1VqSDcMvLguClhs3wXnEGUjcWLbMLv7/vBYj9+E/Tt4WSPevboExtFTtIRK0l0fbPOpv0mWrtrDJjWL+3UfCrGzSOo9Ds4W7rYMbuXfGxyDatnRAUlWJkR3jT+vgots72UcBtkL35I1UIW67kqcOA1a/VsdxVgMLM=,iv:v2quwFfI0Xx2C8fhiVEWCvmBYw6T+LMYiz0LssxWTDo=,tag:mgLR70NgNsOzztiKnmkggA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
