apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:L0awRrOkne0=,iv:d2mHXf58S+SwPdEfsuBgADWVKEIUgZSqCk5c0pClKXY=,tag:VL4UkudZSZM2rvgi4m3oeA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zukJsaKNSeywpegJdR6pB/h65+rKELSU,iv:s1V2ezjWjf61XXjz2Egn4VaCbvkMCjacGAHox0f+24s=,tag:ONO43rGX/mdiGGY3H3Ezmw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:y8bzAJMrSntPgVqULGoegEZfGLm/+6oTwgoHD2GtuDgF7/aMQA==,iv:MP7bhXuuLvwaQAMNjUj58Lm/wMmEAKFK1dK6YNQT9kQ=,tag:ypA3m4bbvhBi3Idvq3JQaw==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:ncHPiJqgs5k=,iv:O5rSnGZ1qtPU0Hpka26EycB2zXyV8QRHKmzFDlBBC3I=,tag:AYf6Y05/lJ1gMD656srBdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZmRNRGEySmNDQ2laVUI5
            QnZ4TitGamdzb1kyWit5T3lXVlNrOFluMmpZCmlrUVFtZFhja2tUUms3ZWRsZWxK
            NWFHZjFUV2dOeGJHUnVaaXcyZkdEWmMKLS0tIHFhKzVUcFB1ZEF2aE5wdFoyeTMx
            WThwcEE3aXNQaEhYR2JZL0JwbXM3Z00KyB+orqMAtXHzi/Ofyd2cWxMBvlLACe6m
            pusocYzqvTCDIpy+dvWKUVwbbwiEruKVypaatk7vjHlFwBEdujEkRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T22:05:24Z"
    mac: ENC[AES256_GCM,data:NfQ4w0k189QEHlQ0+stxmXr41YSuVT7RDH8RdD2SBliCDjX5pE7YTBYOiA4ZiMoExnHQfxsXwD3C5PhW1luVj2wYHvaU0mkUBozNSCUNNDTXX/jW13COboHwTZjKTjp0EyfwaPwiyXBenuhB7qqxpBl7o3ByVKcnbCIrnE2vr3Y=,iv:v/+z7iuSHEHTjwg2uRid0eUPqPdtH9zxOTEcGRqoLBU=,tag:OG8GiVbr5HACdkZekIadOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
