apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G2GTtBe8tzYBD64fR3G2,iv:iCV3ykP1ZwcjwoSUHTtaH5lKwyh4LfmLFRDgcPuoS7k=,tag:S/iA4QK/jrBFWvSh6v2log==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:635kgrSQOGzJl/XGuraWBtcgk2b9mbEe7C/wtQ==,iv:8j/a/MrFSUqSZhldFieYKcUVL5hr9jxrBh3qUYLa4v8=,tag:DJFFSKWlMuFyIS6COzQugw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Gvi/+B2cwrkyM5CiPLlCIVDAiB+6CQSF294RY4pQm0dLt+z2OQ==,iv:49vlFTeZFgeXFwmin6An18yNvLr1lrFtQw4/PSh91B8=,tag:ZcGWNn1nJcNb09zrtThq4Q==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:0DoQdl42Am7dtftjp/Hv,iv:9f9xnv5+mayN21IcECC31FmVQVWEMlXg8K/Rceg4y7E=,tag:p6PjS8AMDCSNl4ICMR72ZQ==,type:str]
    POSTGRES_HOST_ADDRESS: ENC[AES256_GCM,data:fbl6ZffwPK6/je3F,iv:QT2rpT6+wwmR1pDidK6lHBv9RVHs1K90qD3WqNNXKoc=,tag:rJ5957LIcqjXzFAw0RZOIQ==,type:str]
    REDIS_HOST_ADDRESS: ENC[AES256_GCM,data:Oq12y+s0EstzGOoHdg8=,iv:ySsx5awlRvoCaApTjnmlV3UY805vKA9dtK9/yDOclwA=,tag:hruadgGoS6riOhIWQI07Eg==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:ZvNASOOVwrzEL9D2,iv:81OOoKLLjNSFCvmbbpIseAC3pJB3FEnulX8tk8u+dOQ=,tag:ZP5M2CVNqR97BrFvzYSsBA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:A6HAeiUvzgbHuypB,iv:COXchCppXVoUlHqE9so4yUYujvPEbS58dl6Q7cY3QKo=,tag:UKyJ007BW5BD5CfBSZXf4A==,type:str]
    LDAP_OUTPOST_IP: ENC[AES256_GCM,data:0npr7GLixI44qJ4d6Q==,iv:F6riY6gHCORsCGdrjo66tLB9FykaQu/BkT4+HZKJzKU=,tag:/s+/wLXJhuHHNTzSIEizSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGhMaTJzb1g5NG1YT1Ru
            UTZINXVFd2swa2E3dEZxUlVDR0NhUldSM3lVCmoyb3lrRlJsMEtvK3pYVDk2OHdo
            RThHYi9WOG1zcVFZYlUvTURzdHhRc3MKLS0tIEljdkNBUTU0azEvZm90L204QkRy
            WHh3MXdZcFBibW5ieHo4cWxuYi8rcVEKvhChJ0usOe+LnjXvUlFs1Ru+yJ/GIFPH
            qKuwIDD1lFQ4wzvt5HSTieFCBWg2NIdzOJixmb2+isrJjK3DvBWbSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-31T19:32:14Z"
    mac: ENC[AES256_GCM,data:yHYr7uReHD9mymCXOrG/Q4mn1/yQHX1B2e2x7Jpo2tWL+ctzU1hwvxFxdSMBgZZE94F5Gl2Gvn//rJqcjWmYzMs81rsncXib6FTUQjWBa6805RZY9lub2qWlfGsqRdgTXyJut5Dmsz2Ec7EzVsSvUaHOgItZu2vgCTbLL/dWG28=,iv:S1GfHBRUTq8XkzyYpIwXooTOMKpmqyaEyb/tWzFfNOg=,tag:UiU07w15PwmoSaixys2wDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
