apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:L0awRrOkne0=,iv:d2mHXf58S+SwPdEfsuBgADWVKEIUgZSqCk5c0pClKXY=,tag:VL4UkudZSZM2rvgi4m3oeA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zukJsaKNSeywpegJdR6pB/h65+rKELSU,iv:s1V2ezjWjf61XXjz2Egn4VaCbvkMCjacGAHox0f+24s=,tag:ONO43rGX/mdiGGY3H3Ezmw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:y8bzAJMrSntPgVqULGoegEZfGLm/+6oTwgoHD2GtuDgF7/aMQA==,iv:MP7bhXuuLvwaQAMNjUj58Lm/wMmEAKFK1dK6YNQT9kQ=,tag:ypA3m4bbvhBi3Idvq3JQaw==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:ncHPiJqgs5k=,iv:O5rSnGZ1qtPU0Hpka26EycB2zXyV8QRHKmzFDlBBC3I=,tag:AYf6Y05/lJ1gMD656srBdw==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:9k/ZT59SCawYvQjibV1LgzIyd6Q=,iv:Ps1Q7Z4XkoPNkzkfqnnYgScycUQNU08/YKBWTkXpPHE=,tag:QEmAWNJNjUdRaiAkPZ4x/g==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:1KL1vf+EQfuV8j0p8fTaMkwTS+GbeIjFjs8ppeXuaeSo0yWJSJVo0nGT10PIQEMdNmA=,iv:LoUsGmKiZeNoUWoBLYG1YL646VzNmUjPWYCKlf01KiE=,tag:wMY4dAiR7sKMKMbfwH1g/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZmRNRGEySmNDQ2laVUI5
            QnZ4TitGamdzb1kyWit5T3lXVlNrOFluMmpZCmlrUVFtZFhja2tUUms3ZWRsZWxK
            NWFHZjFUV2dOeGJHUnVaaXcyZkdEWmMKLS0tIHFhKzVUcFB1ZEF2aE5wdFoyeTMx
            WThwcEE3aXNQaEhYR2JZL0JwbXM3Z00KyB+orqMAtXHzi/Ofyd2cWxMBvlLACe6m
            pusocYzqvTCDIpy+dvWKUVwbbwiEruKVypaatk7vjHlFwBEdujEkRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T18:49:10Z"
    mac: ENC[AES256_GCM,data:NqWAvMnzWHrqk1/NkESO0vThQ/bQlTNfo595l6695Yrz1BNKMsDZTJI56BS2KyAX0eRpgUPKAL6sKjEa4qPc/asLSh9fct377Axz3NPGegE0efR8ZLDKm34fb4d0/cOTGOZLltWa6pplK47nvVerilxQkD2ytq38AOERa/jFn2k=,iv:wyuq5EIfF/ziTXhCjOuzXZnYJahCo8QwSeeffugcdDU=,tag:Ju5LKlA8P3fFfEpeAz+YRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
