apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G2GTtBe8tzYBD64fR3G2,iv:iCV3ykP1ZwcjwoSUHTtaH5lKwyh4LfmLFRDgcPuoS7k=,tag:S/iA4QK/jrBFWvSh6v2log==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:635kgrSQOGzJl/XGuraWBtcgk2b9mbEe7C/wtQ==,iv:8j/a/MrFSUqSZhldFieYKcUVL5hr9jxrBh3qUYLa4v8=,tag:DJFFSKWlMuFyIS6COzQugw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Gvi/+B2cwrkyM5CiPLlCIVDAiB+6CQSF294RY4pQm0dLt+z2OQ==,iv:49vlFTeZFgeXFwmin6An18yNvLr1lrFtQw4/PSh91B8=,tag:ZcGWNn1nJcNb09zrtThq4Q==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:0DoQdl42Am7dtftjp/Hv,iv:9f9xnv5+mayN21IcECC31FmVQVWEMlXg8K/Rceg4y7E=,tag:p6PjS8AMDCSNl4ICMR72ZQ==,type:str]
    POSTGRES_HOST_ADDRESS: ENC[AES256_GCM,data:d9tp4tFO26wsGGs=,iv:VRUPpHEhyTheo57yVM0t4FHnctoKfodNSybBQf+/0fM=,tag:F7jEMJ87xvwln7HOiLpIXQ==,type:str]
    REDIS_HOST_ADDRESS: ENC[AES256_GCM,data:hRfjeV3UO/5Um3U=,iv:EZV5KyZZ1IZ2llzyyeXE6w+UXw6wkBkqCEi1yRmTINQ=,tag:PvyvLgJI2nr5H7yOtJ0azw==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:ZvNASOOVwrzEL9D2,iv:81OOoKLLjNSFCvmbbpIseAC3pJB3FEnulX8tk8u+dOQ=,tag:ZP5M2CVNqR97BrFvzYSsBA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:A6HAeiUvzgbHuypB,iv:COXchCppXVoUlHqE9so4yUYujvPEbS58dl6Q7cY3QKo=,tag:UKyJ007BW5BD5CfBSZXf4A==,type:str]
    LDAP_OUTPOST_IP: ENC[AES256_GCM,data:SdhnvdWE583PfiayHg==,iv:0EF3bedRu+HOpFvxrdNkwzvy0K07z98sVaRR9SwaFFQ=,tag:rbb9HIz9sWjBIXHVMEO0Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGhMaTJzb1g5NG1YT1Ru
            UTZINXVFd2swa2E3dEZxUlVDR0NhUldSM3lVCmoyb3lrRlJsMEtvK3pYVDk2OHdo
            RThHYi9WOG1zcVFZYlUvTURzdHhRc3MKLS0tIEljdkNBUTU0azEvZm90L204QkRy
            WHh3MXdZcFBibW5ieHo4cWxuYi8rcVEKvhChJ0usOe+LnjXvUlFs1Ru+yJ/GIFPH
            qKuwIDD1lFQ4wzvt5HSTieFCBWg2NIdzOJixmb2+isrJjK3DvBWbSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T23:34:16Z"
    mac: ENC[AES256_GCM,data:eta1vyHv59uoBma/G2sPJwxXDxbpb8oVpMIPX+Vlr45vWKd5M2ePC0ws8Vpy7sHlTDxISm2ws/DJaU7q4bNwpUHwqmV/BuoobR5Xi+twkiUtz3d1kn9wBPp3s7nwd8GbHAvDJD/I0KqcL9+DvOP83UR6Qc/obMji5QvJkR+ZIh0=,iv:PEf4/LUqJ5/7f5+/4INyeOZ19qcf+OtGQIA+Qow1pTg=,tag:uNEx85nY5R0ae4nkvrTiiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
