apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G2GTtBe8tzYBD64fR3G2,iv:iCV3ykP1ZwcjwoSUHTtaH5lKwyh4LfmLFRDgcPuoS7k=,tag:S/iA4QK/jrBFWvSh6v2log==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:635kgrSQOGzJl/XGuraWBtcgk2b9mbEe7C/wtQ==,iv:8j/a/MrFSUqSZhldFieYKcUVL5hr9jxrBh3qUYLa4v8=,tag:DJFFSKWlMuFyIS6COzQugw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Gvi/+B2cwrkyM5CiPLlCIVDAiB+6CQSF294RY4pQm0dLt+z2OQ==,iv:49vlFTeZFgeXFwmin6An18yNvLr1lrFtQw4/PSh91B8=,tag:ZcGWNn1nJcNb09zrtThq4Q==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:0DoQdl42Am7dtftjp/Hv,iv:9f9xnv5+mayN21IcECC31FmVQVWEMlXg8K/Rceg4y7E=,tag:p6PjS8AMDCSNl4ICMR72ZQ==,type:str]
    #ENC[AES256_GCM,data:c4lucb/0cvcS94VsV7mQaRaY1tRWfG2pGLdWd2tptHKwrLlLbA==,iv:wKo6P2gxFNCIeA0MUL7XLH/YlSrSuCOB/j8xy1apEkU=,tag:Tp6otTqREhWbQUIYbMTwIw==,type:comment]
    #ENC[AES256_GCM,data:N80ViqL4HSWgPuJI9Abyu5yighasCe7prAHAF3mdjHwzEg==,iv:xPzm6G9buHsaVwtCf1qibwjY71Vfi2ng7Sooq2HOeRs=,tag:mmZyxuORNBC3wKSaaJZlww==,type:comment]
    #ENC[AES256_GCM,data:o8jcm+/cZ8ptdPtbJnEwdle+dobY7B7RqsS4VwqUcmgQa0P3wrdh6TA=,iv:S4cb3EAZxiz2QNZX24pkDNeahWoNgmv21k8q5KCkqFQ=,tag:qSvPNnpSzLRGDtYIRYIvNg==,type:comment]
    #ENC[AES256_GCM,data:cEgBM7cFiVfEiWG6rsOotBi2tte95T063B7BgN2WoblhHNSuxh3jfhjm,iv:cJTPSm066vg0109IeuMSy80Vd0GLZ4+1RzbYuSWir1g=,tag:wz+pX3jdoZxb0/Fz7oZqcQ==,type:comment]
    #ENC[AES256_GCM,data:+ASsJXud4Iwl9ygvdn+oXTQO9QfWl20wdgegVplWRw==,iv:1H6j701vVz8vMDOCbGuJlq9lxCK0ibfCL7ddRz2SLzE=,tag:cZFeNg/pdfoIQTfVoNkhTQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGhMaTJzb1g5NG1YT1Ru
            UTZINXVFd2swa2E3dEZxUlVDR0NhUldSM3lVCmoyb3lrRlJsMEtvK3pYVDk2OHdo
            RThHYi9WOG1zcVFZYlUvTURzdHhRc3MKLS0tIEljdkNBUTU0azEvZm90L204QkRy
            WHh3MXdZcFBibW5ieHo4cWxuYi8rcVEKvhChJ0usOe+LnjXvUlFs1Ru+yJ/GIFPH
            qKuwIDD1lFQ4wzvt5HSTieFCBWg2NIdzOJixmb2+isrJjK3DvBWbSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T23:14:13Z"
    mac: ENC[AES256_GCM,data:Y9iTfyV5NvWKMTGZHvTQlwpqJuAwof+NS5w/x+pZymCHTisXq3T725NyirI7m1GVR7gYh6HV+v+lNzD7BwkW97xh00HeW0DmAU0RJl7mN6bMIGLLNpVwy3jyBBT/cnGIlAXJEVMTiejrJ3mm84u/MvoqbuhE7PTZHuXLT1klsZU=,iv:GliCODRxhV8annn5DWrbmUsgwDsL+sCvpEmeBz3wq+8=,tag:vR+Eri+UlMPHsUR0u138Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
