apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns
    namespace: kube-system
data:
    Corefile: ENC[AES256_GCM,data:lNTR6EHtYYt+Q8862tIF68becPLRLQoEAlk2w5DiEQy3xz1T6cqvWdhU/2ZhA96u7fRF6BCWDgg+Olz+HvJgUtVGJbc8Q53iqCn6hIjVCnDCH1+cSiKxnWFXvThmD+4L+bIoU8rbD79H9SQXsjqOQIFvMdYmg6e1VqMMSFVIplPM2oKOJcjU1dWxxUtBxN61s2dfJacct1HLzrGaSaeovaNx39P8cz8t+0rXEdJXAqZp0PZONaU+KRdjYaEIpSeMJbplL+xMLo9shfQEe4x1xzyt46PyQrg51qRSLeS+fP0a7ioId+rIOB0hyHApGrnDjOE9oUbu/Csul6VTzH/WEDnYZsOaV1BJd1AVjSEvFtGb3ZEF2RBEOok+ocWgVEqt9LT3kcIBOt3z9EAyiFILrAF6LyJuu0PVHIQWil1F/paIvNw0CMoPYN6GMEzBVclxyPUmTMiDNGiPWBvydc2rDOe9CYZQfFE9dHGLkshj03Hy491L4Ss5L0YBiz7f1HDxGuSRW1RJa+UIRoT1e/KkBvaEW7QCBvQZTn05PxznPO6SH2pXjA3HqqbWO58=,iv:6NlFDMSSHP/T6JNBrhwI/u+uLifYjmAVN8nvvRP4RhM=,tag:jkBjI/pd59TULhZayk/M1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QUpFN1VOMCtGcVZaNlJ3
            NzMxeDdzL2dMR2NTK2NIQStSZzNPVkVESFZjCmN2VFQ2YmhaVHhNaTd0Q0o2ZHVX
            cVA4aEZZRDBQVmpTRVNJbURyT2lJK0EKLS0tIHNsLzFXeERXMnppeTIvSnNtc2xp
            NzdhR1RTR0NINHhPN0JHdlVQdmU0b2sKBSZsJ0Y0eJPcURltC+cM7Xd1ikz/IWvZ
            1jxc4XvgvpEVHWkGH3xeQx7ybtiLZmvi3SEaACM6ocpkYZlx6Lj2FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T15:45:46Z"
    mac: ENC[AES256_GCM,data:dLUg6Ymaw9569rSUg9RpoRPJHQZ7u2ONHdHegRQp/4EMjHdW2yxcLLRzschpwFaVJJtss8Q9EEXP0Cd6GcDsBTWizZ8Mf9Tg6dZpso+iLpoybWYwlBB5o+HFxI1bqlC92m7CUye+AWRR5Fk2dDJnXnIOlIJ9aRUikQTMty4375o=,iv:r9XaQ19VPBHAp9QaylKI8sAy8vPLOvDEs6new1C66Uc=,tag:XF0cbaUFSVVn+bwH3oMgQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
