apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VVsI3zBUIUNiO4ti9bqrDmhyd5hCkaSrgK4jFH6YLgGIMRXNuHafNSvovxAfMgL8tK/XMTKf8tmPuMAse4IOn3uskFflvV9Hs9+ObgSTvbZSQbbZrImGj5exNIut/UAMECV5ustdNlIk4nSM174/7BFArxxdSLrEbA==,iv:oXSMJxJnDROng+fbY/F/XTfxAyPUJRdpbeA/LZ6mekQ=,tag:QQ2ZE6gnR8nLS+6xCN/BCg==,type:str]
    username: ENC[AES256_GCM,data:50WU4Nsv4I4hrA==,iv:oi5IQFKGGLKyE71Uod5Vgr5af7pagyoosILjfhnGnio=,tag:1KkYEyUoUNlA1eA37kJQZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZTNzWGdHYi9BcU42ZTVu
            WEY4bGt5UUJnZUxMR1JwSVp6YmhlRkFJOUFnClpSSSthMFFaSDM0ekF3eHNkV3JQ
            UlJ0ZlBySmJ5U3NsQ2kyYTVsa08ySmcKLS0tIGt5NHFoditLSkswT2ROSjJITXFr
            QUl2eU1zMFZaNXlKMUhMbzZQWmg3cDAKWBtJW93pRkBsJqPnj0VGX0lT/XI91Vwn
            gG4ikOZq5EDTfwE0ORiX39rlZZG3d1HycWWK2Cg/NL4oTEJEdzrflg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T13:25:54Z"
    mac: ENC[AES256_GCM,data:DCe0xQtz7uN/qOT3oXczFh04YxRY2u/gx8mEQyW8KVbTq0JycjfFFQ2VBTVYZrLJ43oGE/GL6nCoFq0KTOrgDWmKcMq/vzOCEEt7oFaIXKu0ebZtKMTMKgWVAyHUCzkaad71bzni3D5xDbvQt+EhzTXIaWCbcK2EOy5Ut25HEGQ=,iv:8C/qO23RIYD4ZDJgvZL15xYkAMyiTGn40sVzG9rstGg=,tag:QpDthFE8JmmkSH4gLHg4HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
