apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zquwz3KH8enZRBBXVVbYjkrXfCr2Ll/WPyBYqPKj2rJB0p6YIhRsh2b2D/1UZDj6ieRrnxhoZFmH9pfGDo/Dwh2Obo2TRXBx963/TiK9nJMH2NmTtazeZicS999s,iv:AYFqpIpf+wODrpONW8EgPILGUKeWLED4SxuG5kVbAcM=,tag:DXAdCF5cwFRGNgQJlwh/cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVDhmZzFXdnR4bURiSnJT
            ZURlRnpSaUpzUFFRTDdiaFZKeXJpKzhvNVJrCkxQWXVKS3FJWFdjVmpYcm1kdFN3
            R0VIV2dUUDdma25zR2F0VVk1bkUyWW8KLS0tIGxSdVdjZ0d0TzcvK0VMaEJYQXI2
            R3R3UlhBY25reTZGVE5sZTQwaWhwTjQKSQ70CZG2850xeVXTym/a6ik3e9tKGvOd
            aUOUtQwUiARE33fHycvVvlIdw+v2MUPN3OyoqnbtgKJOyujYgb7gqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T11:45:02Z"
    mac: ENC[AES256_GCM,data:BVmpyGe7YOJlCngjtfwCFRvBMQOV6toLlElpOxAH338+g3bwNBZppgm6McXWrL9SvP7AQRfCjTZuvOMYL2eRFDCxsMUSkxIWwRMusxAtJZs8UrErMZuQDwxJmBoQRXlAL7t296wzz/DSdwGqQNX6dQmuMra38So2NnjA9LMsSwU=,iv:p3hQPZkZaWjf8Dsl9FtNEHYLqEuDjGpjDAIr0GuEmos=,tag:0wtR+21/+9LrCZOVm0tMgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
