---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-download
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
