apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
