kind: Secret
ansible_user: ENC[AES256_GCM,data:Va75KWM=,iv:ax3rei7TJA3QskNh7nTDEYsIAevj6rCOnKppQbOfL/A=,tag:LR3selrNzCDncHpPQuMVag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tlfd3prf27dqkzej6fhq4ke2usxgxn9nsaevggk04uhgmxr7h4pstrldnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUisxdmNRYm5QcXpqMjlQ
            SmdvakM3S0cvRytKQU9kL2kxNjBJTDJxbUhnCmZHalo4SmwxT0hWNmFpQUJpV05L
            M010WGkyd00wcHkvcmI0YUhwUXVGVEUKLS0tIEFlNld5bUgwSTRqdnJYTGpMYW5M
            bVYxODkwektsYzJkUUZjTERBbExvL1EKeh+xq/iNe9aKJPxx51d9xLMaX6jVL3Cm
            gnRkw/MK9b7uOSByPfyZSYBnXRcXdFJAeiVjilcXnbb+FEushKiRog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T14:29:46Z"
    mac: ENC[AES256_GCM,data:6h2xsecRQNPCC5wDLSiXZ0WJVFtXUKdJHf4LTznUpx0QgSjY219IZ6eHIDpBZhmqoc01j0zmPVt/HloH81oaMnveuQm4npSSbToiADBXRUTKfiXaXR3rgAIFAF1spRGZ/X+ameHbRLm53JucjQMRXa3exDO1unlyiRj1bJO2Gug=,iv:G/xR5mU752RxytPrjSA+PEONtkAz9o9Ma1nsz2FtZMI=,tag:JjWjOAmjqKGyvz4ruSsawQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.8.1
